
:PROPERTIES:
:ID:    test
:END:
#+title: Greek Civ
#+Description: Notes for class


A Brief History of Ancient Greece _ Politics, Society, and -- Sarzz

* Chapter 1 Notes
** Greece In The Stone Ages
-  Hunter Gatherers first entered Greece 40k years ago, during the Middle Paleolithic (Old Stone) Age.
-  Early in the Neolithic is when we started to see domestication of agriculture and animals.
-  Agriculture forced people to settle down permanently and we saw new villages spring up. Eventually communities were formed.
-  Society was more egalitarian. "Head man" would lead the villages and keep it stable.

** Greece in the Early and Middle Bronze Ages(c. 3000-1600BC)
- Bronze was introduced 4k years after the adoption of agriculture.
- As the economy expanded, so did the waelth of their leaders leading to more authority and privleges.

*** The civilizations of the Near East
- Near east was more progressed compared to Balkans and Greece.
- Aegean civilizations rose in the second millenium to tier close contacts with the East.
- Socities advancing made people more dependent on a elite ruling class.
- Early civilizations had enormous influence on the cultural development of the Greeks.

*** The First Greek-Speakers
- Current Hypothesis is that Greek and other Indo-European languages evolved during the long waves of emigrations from an  orginal Indo-European homeland.

**** The Greeks
- Greek language eventually submerged the non-Indo-European "Aegean" languages.

*** The Discovery of the Aegean Civilizations
- Greek speakers entered the Aegean (c. 2000BC) First palaces appear on the island of Crete signaling that the cretans had joined the company of complex state societies.
- Note: Cretans were not Greek-speakers
- Found evidence of a mighty warrior king in the site of Mycenae.
- Sir Arthur Evans discovered the palace complex of Knossos on Crete. He named this first Aegean civilization "Minoan" after the king Minos.

*** The Minoans
- First settled around 7000BC by neolithic farmers and stock-raisers.
- The palaces economies were based on storage and distribution. Food and other products were paid as taxes, then collected and stored.
- Major gap between people and ruling class. The people lived modest lives while funding the opulent ifestyles of the ruling class.
- King was an embodiment of the state(supreme power).

*** Minoan Art and Architecture
- Major influence from the civilizations of the Near East, epscially Egypt.
- Cretans developed their own distinctive stlye and spirit.
- Minoan art today is admired for its sophistication, vitality, and exuberance.
- Insight on how the people viewed themselves through paintings.

** Greece And The Aegean In The Late Bronze Age(c. 1600-1150 BC)
*** The Early Mycenaeans
-
