 * Test
:PROPERTIES:
:ID:    test
:END:
#+title: Greek Civ Class Notes
#+Lecture Notes

* 08/28/2025
** Bronze Ages: Cycladic and Minoan Cultures
- Cyclades Islands had more progress in comparison to the Peleoponnesus amd Crete. Mainly due to location. Allowed for easier communication and trade.
- Different cultures throughout the bronze age in all areas. Main distinction is through pottery style. Other crafts didnt see too much change over time. Pottery changed the most throughout generations.
** Discovery of Greek Bronze Age
*** Troy
- Heinrich Schliemann was a german buisness man. Had become intresed in ancient Greek history due to childhood. Accured a fortune due to buisness ventures. Set out on a journey to discover Troy.
- Buildings were built up through generations, making it seem like a artificial hill.
- Troy has so many layers with cities built on top of cities. Making it extremely difficult to excavate.
- Schliemann messed up and mixed all the time periods together but got lucky and discovered artifacts such as jewelry.
- Ottoman Empire caught him stealing artifacts, and banned him from excavating.
- Began excavating the site of Mycenae and wanted to find the tombs of the king(agnomemon) during the troy war.
- Discovered the gold mask of a king before agnmaomenm.
*** Knossos
- Sir Arthur Evans began excavating the site of Knossos.
- Discoverd evidence of a prior civilization due to old heiroglyhic stones that gave him clues.
**** Mythical Associations:
- Minos was the son of Zues.
- Thessius was a myth hero who went there to slay a minotaur.
*** Cyclades
- The islands are very small and rather barren. Settlements were small as well.
- Staple crops were olives, grapes, wheat, barley and pulses.
- Trade was very important to the economy allowing certain indivduals to gain wealth.
- Very little was known about the cyclades at this time.
- Due to poor terrain, settlements were very short lived.
- certain groups were able to control the trade in valuable raw materials and finished products such as metals, obsidian, marble vessels, figurines, pottery, etc.
- Common culture began to develop through these trading contracts.
- The early Cycldian/mioan lasted about 1000 years.
- The creation of metal tools and weapons led to quick societal development in everday work, but more importantly, warfare.
** Great leap forward in social complexity on Crete(c. 2000BCE)
-Continued next class.
* 09/02/2025
** Review last class
- Due to how close the islands were, trade was very active, leading to the quick development of the cyclades.
- Obsidian was very valuable due to its sharpness. Used for weapons and tools.
- Introduction of copper tools was very important, great leap forward in their development.
- Mini arms race would begin due to this, as everyone wanted to not be behind in warfare when it comes to weapons.
- People who owned the means of production would rise to power during this time.
- Transitioned from egalitarian society into a two-tier and even to a mutli tier society.
- Music and instruments were a way for poets and "musicians" to tell stories about gods and heros.
- Figurines and statues emphasized things they thought were important such as fertility and seafaring.
** Great leap forward in social complexity on Crete(c. 2000BCE)
- Start to see new things
  1. Monumental Architecture(Palaces)
  2. Literacy
  3. Complex Palaital Administration
  4. State formation
  5. Politcal and economix centralization.
- Crete is the largest island in the Aegean. It was very large and fertile in comparision to the Cyclades. Language was not Greek yet.
*** Early Minoan II (2700-2300 BCE)
- Contemporary with EarlyCycladic culture and Old Kingdom Egypt
- Settlements were small and usually built on low hills.
** Emergence of the Minoan Palaces( MMI B, c. 1900 BCE )
- The palaces were the political religious, economic, and administrative centers of a number of regional states located throughout the island of Crete.
- Specialized and full time labor emerged. Really the start of the multi-tiered society.
* 09/04/2025
** Minoan Cont.
- Bulls and Godesses were very prevalent in minoan culture, giving us an idea of what their ideological values were.
- Syllabic scripts cotain about 90 signs with some ideograms representing ideas or words.
- Undeciphered, but a few words are known. Numbers are known and idicate that large amounts of produce were being moved.
** The Mycenaeans (1600 - 1200 BCE)
*** The Origins of the Greeks
- People in Neolithic and Early Bronze Age did not speak Greek, neither did the Minoans
- Greek is a later branch of the Indo-European language that originated in Central Asia.
*** Mycenaean Culture
- Greek speaking people (Linear B script)
- Development from local warrior aristocracties to palace-centered states with wide trade networks across the Mediterrainian.
- Mycenaean age was the age of heroes. According to Homer, all of the heroes lived during this time.
- Homer uses the terms Achaeans of Danaans when refering to the ancient greeks in his epic poems.
* 09/09/2025
** Mycenaeans Cont.
*** Mycenean Culture
- Came in the late Brozne Age
- The citadel of Mycenae is what the culture was named after.
- Homer refers to the bronze age as the age of heros.
*** Grave Circles at Mycenae (Late Helladic I, c.1600 - 1500 BCE)
- Some of the earliest evidence for Mycenaen culture comes from two grace circles at Mycenae
- Minoan palatial culture was at its height in this period. Myceneanes learned from them.
- Toms would be become larger, richer and fewer. (wealth going to less and less people)
- Conspicuous consumption was on a large scale.(gold and weapons)
- Wars appear to have been waged more for personal gain rather than common gain.
* 09/11/2025
** Dark Age and Gerometric Greece (1150 - 700 BCE)
*** End of the Bronze Age and Mycenaean Culture
- Widespread destruction all over the Easatern Mediterranian and Near East around 1200 BCE
- Very violent and chaotic period.
- Not just war, but a series of events such as natural disasters, over the couse of around 100 years.
- Top down heavy system, when the rich collapsed, everyone else did as well.
- Citadel in Tiryns was violently destroyed at the end of LH IIB (1200 BCE) indicating a massive war.
**** Possible scenarios for collapse
- Overexplotation of the land, deforestation, soil erosion, famine and civil strife.
- High costly wars
- Palaces hoarding the wealth.
- Wars on the greek mainland
- Mercanaries fighting in these wars turned to piracy and raiding, crippling trade?
*** Dark Age of Iron Age Greece
- 1200 - 1000 BCE was a period of great civil unrest.
- Poverty, disunity, violence, isolation, and recession.
- Depopulation and resettlement.
- Tin was in short supply after the collapse of palaces.
- Iron ore was very common.
:- By 950 BCE, iron completley replaced bronze as a utilitarian metal.
- Iron attracted Phoenician merchants to Greece and italy, who taught them how to work the new metal.
**** Iron Age Life
- Households were the primary social units. Activities and production continued as before, but no taxes were paid.
* 09/25/2025
*** Later Dark age
- Now the type of government shifted into a polis.
- There was now an oligarchy class, with a selct few families owning majortity of the land and owning most of the wealth.
-
*** Government of the early Greek Polis
- Basileus office was abolished in favor of collective rule of the few(oligarchy)
- Power and wealth was now based on farming and land ownership
**** The Aristocratic Council or Boule
- The council drafted laws and made official policy.
- the council consisteed of former archons and magistrates. Membership was for life.
**** Assembley of Citizens
- The power of the assembly decreased in the 7th century.
- Wealth restrictions were imposed on membership excluding the poorest citizens from voting.
- Meetings and discsussion were curtailed by order of the council.
**** Social Division in the Early Polis
- Sharp divisions between the aristocracy and the common people.
 hoi agathoi(good ones)
 hoi messoi(middle ones)
 hoi kakoi(the bad ones), or hoi polloi (the many)
- the rich became more rich through specialized agricultre or cah crops such as wheat, barley, olives, grapes.
- People would fall into debt, in a time where slavery was normal. Debt slavery was very common during this time.
*** The Lower and Middle classes and the growing Debt Crisis
- Poor farmers often rented land from aristrocats, worked as sharecroppers.
- Others would mortage land and pay with the produce.
- Many fell deeper into debt becuase of high interest loans, droughts, etc.
- The middle class was the majority, and were self sufficient. Upward change was possible but very rare.
**** Citizenship in the early polis
- members were all citizens, no equal rights though.
- women, foreigners, ex-slaves and such, had no right to participate.
- non-aristocratic middle class could vote, but could not hold public office.
- rich landowners became predatory lenders(high interest loans)
**** Colonization
- Colonialism brought a lot of oppurtunities. Started in around the 8th century.
- Were lured by the promise of abudant rescources
- Mother cities or Metropolies chose the sites for colonies and they chose leaders oikistes to set up  and govern the colonies.
- The oikistes was always an aristocratic male. Would lead the colonists, establish defences, sanctuaries. Basically a lot of responsibility.
- Fire would be brought from the mother city, but the colony apoikia(home away from home) was considered a independent polis.
- Many greek colonies were formed along the coasts of Italy, especially sicilly.
**** City Planning
- In the colonies, cities were based on a grid system.
- The mother cities were agglomerations that grew organically over time.
- public spaces, cemeteries, sanctuaries, and residential quarters were all demarcated.
** The Rise of Tyranny and Hoplite Warfare
*** Greek Tyranny
- Political phenomenon that began at around 670 and ended in around 500 BCE.
- The rise of tyrannies was one of the first real documented events in Greeky history.
- Earliest refrences to tyrants had no distinction between tyrants and kings.
- Aristotle, in the 4th century, wrote the difference was that a king ruled by law and a tyrant ruled unconstitutionally.
- More than likely and anachronism. Greeks poleis had no written constitutions before c.650 BCE
- In later sources, including aristotle, identitfy them both unconstituional rulers and lawgivers.
- Cities such as corinth had gain incredible wealth due to geogrpahical location, leading to some of the earlies tyrants being from there.
*** The Social Setting
- 7th century government of the plis was controlled by the oligarchs
- They were still referred to as basileis, but they were not chiefs in the homeric sense.
- They were magistrates and members of the aristocratic boule.
- Holding much power lead to corruption and turned into fights between aristocratic factions(stasis - taking a stand)
- Lower and middle classes were exploited through debt slavery and much of what was talked about earlier.
- Social fabric of the polis was unraveling.
**** Hesoid
- Does not mentions tyrants, refers to corrupt Basilieus.
- The chaotic situation is what gave birth to tyranny.
- Early greek tyrants are given power by the demos(people) to bring order and laws.
- Promoted themselves as "bringers of justice"
*** Appeal of Tyranny
- Many poleis thrived under the tyrants.
- Improved cities through infastructure, new buildings such as temples and harbors.
- Created many new jobs where people were able to now be paid in cash.
- Trade and commerce flourished under the tyrants.
- Gained support of rich merchants, craftsmen, the poor and middle class farmers.
- Tyrants would start to get a little too greedy and would turn into the tyrants we know today.
- Eventually lead to the tyrants being overthrown for different systems.
*** Hoplite Warfare
- Phalanx formation
- Since the gear was somewhat expensive, limited to middle class
- lower class people would be the light infantry, trying to disturb the enemy phalanx
- A hoplite was a heavy infantry soldier
- Emerges in the 7th century with the expansion of the polis
* 09/30/2025
** Ptoto-Archaic/Orientalizing Period(7th Century BCE)
- Dramatically increased contacts with the east, particulary with Phonecicians and Egyptians
- Greek artists and craftsmen appropriated many eastern styles and motifs
- Dramatic expansion of Panhellenic ideals and greek identity
- Intense competition of poleis, Tyrants were rampant
- Building boom that stimulated the local economies and would ressult in economic diverrsity
- Vigorous Trade and colonization in this period brought greatear wealth in the form of commmodities, also new technology.
** Corinthian Pottery
- The great mercantile city of Corinth became a major producer and exporter of Orientalizng fineware.
- The geometric patterns of the 8th century were rejected in favor of animal frirezes and vegetal motifs
** The development of Architectural Orders
- The Doric Order developed on the greek mainland and spread to western colonies
- The Ionic Order developed in the cyclades and near east.
* 10/07/25
**  Sanctuariers in Archaic Greece
*** Greek Sanctuaries
- The proliferation of relgious sanctuaries beginning in the 8th century, was integrally related to the rise of the polis.
- An increase in deications at sanctuaries coincided with a signifcant reduction in competitve displays in the cemetaries.
- Greak sanctuaries consisted of 3 basic elementsL
  1. An altar for sacrifice
  2. A temple to house both votive offerings and a cult statue
  3. A temenos to demarcate sacred space
- Before 8th century, these religious activities and sacrifices were conducted in natural settings including caves, sacred groves, beaches or in the house of the basileus
Sanctuaries were located in three principle areas
 1. The city (centralization and celebration of common a ideology)
 2. The countryside (these sanctuaries often served to unify the urban and rural population and to demarcate borders of the polis)
 3. Interstate sanctuaries (Established in areas not under the control of a particular polis)
**** interstate (Panhellenic) Sanctuaries
- The importance of these interstate sanctuaries was twofold.
- First, they acted as neutral venues of aristocratic display and interstate competition.
- Expensive objects of gifts were offered ot the gods and athletic competitions were held.
- A second reason for their importance was the establishment of oracles.
* 10/09/25
** Archaeological Evidence
- Alhtough there is some evidence for cultic activity in the late Mycenaean period it does not appear to have continued unbroken into the Iron Age
- Renewed cultic activity begins again in the 9th century BCE
- Offering og tripods and figuriens date to this period.
- by 8th centruy, became a very important pan-hellenic sanctuary.
*** Conclusions
- Sanctuaries and games may have had their roots in the Homeric Dark age past, but they were really a phenomenon that grew in tandem with the new form of political organization we know as the polis.
- Pan hellenic sanctuaries served as venues for elite and state competition, where athletes could demenstrate their arete and win kleos bringing glory to their polis.
- The oracles established at these sites served as arbiters in political disputes, which made a significant impact on the history of Greece.
- The result was a dramatic advancements in the arts, in knowledge, and in politics.
** Sparta
*** Archaeological Evidence
- When compared to other city-states, not much is left.
- Spartans were not great builders and lived in simple dwellings
- They were extremely conservative and traditional.
- They preferred a harsh, tough life over comfort and luxury.
- No luxurious tombs, only given to people who died in war or during childbirth.
*** Helots, Perioikoi, and Social Hierarchy
- Sparta conquered the laconian plain and reduced the inhabitants to slave-like status.
- These people were referred to as Helots
- There were also non-Spartans who lived near the outskirts of the city were known as Perioikoi.
- The

- In the 8th century, the Spartans attacked neighboring Messenia (First Messenian War)
- The Messenians lost and were reduced to Helot status.



* MIDTERM REVIEW

** Dates of Bronze Age
3000 BCE to 1150 BCE (includes early middle and late)
- Minoans orginiated from Krete
** Minoan
- Minoan Palace functions were, administrative, politcal and religious. All built around central core. Served as a storage through the storage magazines. Included Residential area.
- Linear A script
** Mycenean (1600 - 1200 BCE)
- Originated from the mainland around the late bronze age.
-  named after city of mycenea. Homer called them the acheans
- The relationship with the Minoans was a trade relationship. We see minoan resources in mycenenan graves, pointing to the fact that there was trade.
** Graves, look back at notes above
- Grave circle B is the earlier one, A is the later one. Can see over time wealth was consilidating.
** Late Mycenaean Period  ( 1425 - 1200 BCE)
- Ruise of the palace centered states. Centralized waetlh and administration. Multi tier hierarchy begins to form.
- Wanax is a king. Would meet dignitaries would had an audience with the king.
- Megaron
- Hearth is a big fire place that is a sacred place/center of a palace.
- Tholos tombs suggest another connection to Crete. They became popular during the late mycenean period especially for important people.
- Linear B script. It was Greek where A wasnt. Branch of Indo-European. Deciphered.
- Slabs that had writing were usually about inventory in the palace. No real literature. The scribes were the literate ones
- Linear B administration.
-
** End of the Bronze Age
- Destruction of the palaces. Possible reaasons above. palatial system.
** Dark Age Greece or Iron Age
- Early 1150 - 900 BCE
- Late 900 - 750 BCE
- Called dark because of reasona like poverty, natural disasters, destruction of arts and literacy. More reasons above.
- Aspidal building of Lefkandi 10th cent. BCE. The significance was that the house was for the baslieus. Prior baselius is buried along with wife and horse. He is creamted while she is not. Cremation was associated with heroic burials. Turned into a monument/hero shrine.
- Lefkandi was a rich community due to phonecian trade. We see muuch phonecian jewlery. Were trading for iron ore since tin became scarce. Prior trade routes collapsed with the dark age so iron was their substiture.
** Homer
- Gave greeks a since of identity with pan-hellenism.
- Was born in the asia minor area. 2 major works are illiad and odyssey. Epic poems were sung and performed with a lyre.
- Greeks v Trojans, Greeks won
*** Homeric Society
- Doesnt accuratley portray Mycenaean society, more accuratley reflected dark age.
- Define Terms.
- Demos is a group of people within a district. Several settlements including associated farms and pastureland. Each town had a basileus and the main town was headed by a paramount basileus. Came from aristocracy.
- An Oikos consisted of the house itself, the family, and the property, including acncestral land(kleors), animals and slaves. Klaros . Father ran the household
** Government in the Late Dark age
- Boule was a council of the Local chiefs, basilieus and paramount basileis. The assembly including the citizens ( The men of fighting age).
- Xenia was the concept of hospitality. Couldnt just walk into other cities. Needed someone to vouch for you.
** Late Geometric Period ( 760 -700BCE)
- Called geometric because the patterns seen in their art. Also known as the Geometric Renaissance
- Greece colonization was popular as people wanted to get better land to make a fortune and not be stuck with the infertile land. Went to Italy and Sicilly.
- Phonecians were from the liventine coast. Founders of the current alphabet in Greece. Better since it sounds like the word, whereas the symbols didnt soud like how they looked?
- Developed by adding vowels in and becomes the alphabet that the romans and we use today.
- Giant cvases were used as tomb markers. Scenes on the vase representing heroic themes showing a sign of status.
** Religious sanctuary
- Temple dedicated to a God or Godess. Was there for offerings and the house of the diety.
- Locations above and mor notes above.
- key to the concept of synoikism. synoikism is the concept of bringing the household and village together. all under one political unit.
- Temples became larger and larger over time due to competition between the polei.
- Votives are personal gifts for divine favor. Ex: tripod. Offering these votives shows status and wealth, and no votives was disrespectful to the gods.
** Greek world in the 7th Century BCE
- Firmly in Archaic Age (750-480).
- Known as orientalizing period.
*** Government of the Early Greek Polis
- Polis is now elected officials and citizens. The city and surrounding territory. referred to as city state as well.
- Power wwas divided with the election of the magistrates where everyone had term limits. if they did good, they would go on to serve in the boule or the council.
- Hesiod portrayed the basileis as corrupt whereas homer revered them.
- Debt slavery became a big problem during this time.
- Assembly of citizens started to lose power.
*** Docial division in the early polis
- Sharp divisions between aristocracy and the common people
  - hoi agathoi ( the good ones)
- hoi mesoi ( the middle ones)
- hoi kakoi ( bad ones) or hoi palloi ( the many)
*** Citizenship
- Members of all three classes were citizens, but were not equal in rights.
- woman, ex slaves could not particiapte in politics.
